import "server-only";

/**
 * The concierge's perfumery education — everything it may claim about perfume
 * itself, as opposed to the live catalogue (which arrives separately as a
 * digest plus tools).
 *
 * Authored from researched fact, phrased tersely because every word here is
 * paid for on every message. Nine sections, uppercase-labelled so the model
 * can cite them internally. DUBAI_SEASONALITY is the load-bearing one: the
 * store sells in a climate where a fragrance decision is a thermal one — the
 * same doctrine lib/quiz.ts encodes in its climate question.
 *
 * BRAND_HOUSES names well-known "inspired by" relationships (Armaf trades on
 * them openly). The agent is instructed elsewhere to discuss these tastefully
 * — "often compared to" — and never to disparage either side.
 */

export const KNOWLEDGE = `PYRAMID
A fragrance is engineered in three volatility tiers. Top notes are the most volatile molecules — citrus (bergamot, lemon, grapefruit), light aldehydes, herbs, light fruits — registering instantly and largely evaporating within 5-30 minutes; what a customer smells on a test strip in the first minute will not represent the scent an hour later. Heart notes emerge as tops fade, roughly 10-30 minutes in, and dominate for 2-4 hours: florals (rose, jasmine, geranium), spices (cinnamon, cardamom, saffron), medium-volatility fruits — the fragrance's true character. Base notes are heavy materials — woods (sandalwood, cedar, oud), resins (labdanum, benzoin, amber accords), musks, vanilla, patchouli, vetiver — perceptible from about 30 minutes and lasting 6-12+ hours, sometimes days on fabric; they also act as fixatives, slowing evaporation of lighter molecules. The drydown is what remains after tops and hearts fade: always judge a purchase on the drydown, 30+ minutes on skin, never the opening.

CONCENTRATIONS
Concentration is the percentage of aromatic oil in the carrier, usually alcohol. Eau fraiche 1-3%, 1-2 hours. Eau de cologne 2-5%, about 2 hours, citrus-forward. Eau de toilette 5-15%, 4-6 hours — daytime, office, hot weather. Eau de parfum 15-20%, 6-10 hours — the evening default and the most common Gulf-house format. Parfum/extrait 20-40%, 10-16+ hours, worn closest to skin. Attars and concentrated perfume oils are alcohol-free, at extrait-level concentration or higher, dabbed on pulse points rather than sprayed; they project less but last very long and wear close to the body — suited to mosque wear, layering under a spray, and sensitive skin. Higher concentration means longer wear and usually a softer, less alcoholic opening, but not automatically stronger projection; formula matters.

FAMILIES
The fragrance wheel's four main families map directly onto this store's four catalogue groups. Fresh & Aquatic is the fresh family: citrus (bergamot, lemon, neroli), aquatic/marine (calone, sea-breeze accords), green (cut grass, galbanum), and aromatic (lavender, rosemary, sage with woods — classic barbershop masculine territory, including the fougere structure of lavender, oakmoss and coumarin). Floral & Sweet spans the floral family — soliflores, bouquets, heady white florals (jasmine, tuberose, orange blossom) — plus the gourmand crossover of edible notes (vanilla, caramel, praline, coffee, tonka). Woody & Oud covers oud/agarwood (animalic, resinous, the signature Gulf note), creamy sandalwood, earthy-smoky vetiver and dry cedar, plus mossy chypre structures. Amber & Oriental is the amber family, the heartland of Arab perfumery: spicy (cinnamon, clove, saffron), sweet (vanilla, benzoin), resinous (labdanum, frankincense, myrrh). The store also reads every composition on six axes that cut across these: fresh, floral, sweet (vanilla and gourmand facets), amber (resinous warmth), woody, and spice (cinnamon, saffron, cardamom). Adjacent families blend well; opposites contrast.

SILLAGE_LONGEVITY
Three distinct measures. Projection is how far scent radiates from a stationary wearer — the scent bubble. Sillage is the trail left in the air as the wearer moves. Longevity is how long scent remains detectable on skin, including the intimate skin-scent phase after projection dies; a fragrance can be long-lasting yet quiet (many attars), or loud early then short. Drivers: concentration and formula (amber/woody bases outlast citrus by design); skin type — oily, hydrated skin holds scent longer, dry skin loses it fast, so an unscented moisturizer before applying measurably extends wear; and climate — heat and humidity amplify projection but speed evaporation. Fabric, especially cotton and wool, holds scent far longer than skin but does not warm and develop it, and oils can stain. Spray pulse points (wrists, neck) and never rub wrists together, which crushes top notes.

DUBAI_SEASONALITY
Summer (roughly May-October, 40-45C with high coastal humidity) turns every fragrance louder and shorter: heat accelerates evaporation, burning through top notes fast, while humid air holds scent close to the body. Heavy sweet, gourmand and amber compositions — vanilla, tonka, thick resins, syrupy oud-sweets — amplify into cloying territory outdoors. Fresh families survive best: citrus, aquatic/marine, green, light musk, airy florals. Summer daytime outdoors calls for one to two sprays of something fresh; longevity improves if some spray goes on cooler skin (chest, inner elbows) rather than only hot pulse points, which burn scent off faster. The counterweight is that most Dubai life happens in aggressive air conditioning — malls, offices, cars — which cools skin and mutes projection: a scent that felt loud in the car park sits close indoors, and pure citrus can vanish entirely in AC. A daily scent must handle both extremes in one outing; fragrances with dense woody, musky or resinous bases hold the transition best, and doses should stay moderate on AC-heavy indoor days. Winter (November-March, 15-28C days, desert evenings below 15C) is the rich-fragrance season: cool air slows evaporation, letting oud, amber, spice, leather, tobacco and vanilla develop properly instead of shouting. Winter evenings — desert safaris, rooftop dinners, outdoor majalis — are exactly when statement Arabian perfumery performs at its best. Rule of thumb: fresh and light by day and in summer; rich and warm by night and in winter; afternoons sit between, leaning fresh outdoors and warmer once indoors for the evening.

OCCASIONS
Office and business: moderate sillage — soft musks, clean woods, light attars; avoid room-filling projection in shared AC spaces. Majlis and family gatherings: traditional oud, bakhoor and amber are welcomed and expected. Weddings: full statement scents — heavy oud, rose-oud, saffron, amber; guests often receive perfume in gift bags. Gifting: perfume is a premium default gift in the UAE for Eid, weddings and business; oud and musk compositions signal cultural literacy, and alcohol-free attars are the safest religiously considerate choice. Day errands: light and fresh. Evening events: richer and louder is acceptable.

LAYERING
Order runs heaviest to lightest: bakhoor smoke on fabric first, oil on skin next, spray on top; never spray alcohol on delicate silks. Safe pairings: musk or amber oil under almost any spray (adds longevity, rarely clashes); rose plus oud, the classic Khaleeji pairing; vanilla plus oud, where cream softens oud's edge; saffron-rose-oud; amber plus musk for evening; citrus over light musk for summer. Principles: match or echo base notes, contrast heart notes gently, and pair one dominant scent with one softer one — two equally loud perfumes smother each other. Avoid stacking two heavy sweets in summer heat and sharp citrus over heavy animalic oud.

GULF_CULTURE
Oud is agarwood: heartwood of Aquilaria trees that, when wounded and infected by a mould, soaks itself with dark aromatic resin over years or decades. Only a small fraction of wild trees produce it and the species is threatened, so quality chips command extraordinary prices; most affordable oud perfumes, including Gulf mid-range houses, use reconstructions and synthetic oud accords — normal at these prices, not a flaw. Bakhoor is oil-soaked wood chips burned over a mabkhara; households scent rooms and pass garments and hair through the smoke before dressing. Dehn al oud is distilled agarwood oil; attar more broadly means concentrated alcohol-free perfume oil, and alcohol-free formats are preferred by many observant Muslims for prayer, Ramadan, Eid and Hajj. Fragrance is hospitality: in the majlis, hosts circulate the mabkhara among guests and may offer oud oil, and accepting is courteous. Scent signifies respect, cleanliness and welcome, not vanity.

BRAND_HOUSES
Rasasi, founded 1979 in Deira and still family-owned, is one of Dubai's oldest houses, manufacturing in Jebel Ali since 1986 and positioned a notch above the value brands with original mid-range compositions in both Western and traditional Arabic styles. Its flagship Hawas for Him (2015) is a fresh aquatic-fruity scent often called the king of budget aquatics, unusually long-lasting for the genre, with many flankers. La Yuqawam Homme is a smooth saffron-leather often compared to Tom Ford Tuscan Leather at a fraction of the price. Lattafa, with roots in 1980 and an official launch in 1992, is the highest-volume Gulf export brand: the most aggressive value pricing of the six, heavy sillage, ornate bottles, and a mix of original orientals and openly inspired-by work. Khamrah (2022), a boozy cinnamon-date-praline gourmand, is widely acknowledged as inspired by Kilian Angels' Share; viral Yara is a creamy floral-gourmand; Asad is a dark coffee-tinged night scent in Dior Sauvage Elixir territory. Armaf, flagship of Sterling Parfums (Dubai, 1998), is explicit about its mission: honest homages to famous scents at budget prices. Club de Nuit Intense Man (2015) is famously close to Creed Aventus — smokier, sharper, stronger projecting, at roughly a tenth of the cost; Tres Nuit works Green Irish Tweed territory. French Avenue, the premium line of Fragrance World, is the most modern-niche styled of the budget houses: extrait and EDP concentrations, minimalist heavy bottles, priced above Lattafa's core range. Liquid Brun (2024) is its breakout boozy praline woody-gourmand for cooler evenings; Vulcan Feu is a very loud mango-praline projection monster. Afnan (2007) is a mid-range house built on viral performers: 9PM, its oriental-vanilla night flagship, is openly an homage to Jean Paul Gaultier Ultra Male — sweeter, louder, 8+ hours at about a third of the price — with 9AM as its fresh daytime counterpart; the Supremacy line includes respected Aventus and Hacivat interpretations. Al Haramain is the heritage house: founded 1970 in Makkah as an agarwood trading business, now Dubai-headquartered, its name meaning "the two sanctuaries". It credibly serves traditionalists with genuine attars, bakhoor and oud alongside Western-style sprays. Amber Oud Gold Edition, its fruity-sweet modern bestseller, is widely marketed as a Baccarat Rouge 540 alternative though honestly fruitier and more candied; L'Aventure (2016) is its lighter, fruitier Creed Aventus interpretation.`;
