-- ===========================================================================
-- GENERATED BUNDLE — migrations 38 → 43, concatenated in order.
--
-- Paste this whole file into the Supabase SQL editor and run it once.
-- It is safe to re-run: every statement is idempotent or guarded.
--
-- Regenerate with:  bash scripts/build-migration-bundle.sh
-- Source of truth remains supabase/migrations/*.sql — do not edit this file.
-- ===========================================================================


-- ─────────────────────────────────────────────────────────────────────────
-- 38_fix_admin_trust.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Migration 38: Close admin-privilege escalation paths in signup handling
-- ════════════════════════════════════════════════════════════════════════════════
-- Fixes three vulnerabilities in the original 04_customers.sql definitions:
--   1. handle_new_user() copied client-supplied raw_user_meta_data->>'is_admin'
--      into customers.is_admin, so a self-service signup could mint a real admin.
--   2. handle_new_user() special-cased email 'admin@gharib.com' to force admin,
--      and DELETEd any existing customers row with the same email first — signing
--      up with that address hijacked the seeded admin account.
--   3. is_admin() ran SECURITY DEFINER without a pinned search_path.
--
-- OPERATIONS NOTE (run once, manually, as the database owner / via the Supabase
-- SQL editor — NOT part of this migration): promote the real store-owner account
-- after they have signed up normally:
--   UPDATE public.customers SET is_admin = TRUE WHERE email = '<owner-email>';

-- 1. Pin search_path on the admin check
CREATE OR REPLACE FUNCTION public.is_admin(user_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN COALESCE(
        (SELECT is_admin FROM public.customers WHERE id = user_id),
        FALSE
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- 2. Rebuild the signup trigger: never trust client metadata for privileges,
--    never delete existing rows, no hardcoded admin email.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    v_first_name VARCHAR(255) := '';
    v_last_name VARCHAR(255) := '';
    v_phone VARCHAR(50) := '';
BEGIN
    IF new.email IS NULL THEN
        RETURN new;
    END IF;

    IF new.raw_user_meta_data IS NOT NULL THEN
        v_first_name := COALESCE(new.raw_user_meta_data->>'first_name', '');
        v_last_name  := COALESCE(new.raw_user_meta_data->>'last_name', '');
        v_phone      := COALESCE(new.raw_user_meta_data->>'phone', '');
    END IF;

    -- New signups are never admins; promotion happens only via direct SQL
    -- by the database owner (see operations note above).
    INSERT INTO public.customers (id, first_name, last_name, email, phone, note, total_spent, orders_count, is_admin)
    VALUES (new.id, v_first_name, v_last_name, new.email, v_phone, 'Auto-registered Privé Member.', 0.00, 0, FALSE)
    ON CONFLICT (email) DO NOTHING;

    -- Link historical guest orders for this email to the new account. The orders
    -- SELECT policy already grants access by email = auth.email(), so this adds
    -- no visibility that the email-based policy does not already grant.
    UPDATE public.orders SET customer_id = new.id WHERE email = new.email AND customer_id IS NULL;

    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;


-- ─────────────────────────────────────────────────────────────────────────
-- 39_rls_lockdown.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Migration 39: Lock down anonymous access to money- and PII-bearing tables
-- ════════════════════════════════════════════════════════════════════════════════
-- Replaces the sandbox-era policies from migrations 10, 12 and 13:
--   • abandoned_carts was world-readable and world-writable (checkout PII:
--     emails, phones, full shipping addresses).
--   • orders / order_items / order_tracking accepted anonymous INSERTs, so
--     anyone with the public anon key could forge orders at arbitrary prices.
--   • order_tracking was world-readable.
--   • product_collections accepted anonymous INSERT and DELETE (merchandising
--     was publicly mutable).
--   • customers "Users read/write own profile" was FOR ALL, letting any signed-in
--     user UPDATE their own row INCLUDING is_admin = TRUE (privilege escalation).
--
-- After this migration, checkout and abandoned-cart capture go exclusively
-- through the SECURITY DEFINER functions introduced in migration 40
-- (place_order, capture_abandoned_cart, track_guest_order), which the app
-- calls from server route handlers. DEPLOY NOTE: apply 38–40 together with the
-- app release that introduces /api/checkout — the old client-side inserts stop
-- working the moment these policies drop.

-- 1. abandoned_carts: no anonymous access at all (admin policy from 12 remains)
DROP POLICY IF EXISTS "Allow public insert on abandoned_carts" ON public.abandoned_carts;
DROP POLICY IF EXISTS "Allow public update on abandoned_carts" ON public.abandoned_carts;
DROP POLICY IF EXISTS "Allow public select on abandoned_carts" ON public.abandoned_carts;

-- 2. orders / order_items: drop anonymous INSERT (owner-scoped SELECT from 10
--    and admin FOR ALL policies remain; inserts happen inside place_order())
DROP POLICY IF EXISTS "Allow public insert on orders" ON public.orders;
DROP POLICY IF EXISTS "Allow public insert on order_items" ON public.order_items;

-- 3. order_tracking: drop anonymous INSERT and world-readable SELECT;
--    scope SELECT to the order's owner (guests use track_guest_order())
DROP POLICY IF EXISTS "Allow public insert on order_tracking" ON public.order_tracking;
DROP POLICY IF EXISTS "Allow public select on order tracking" ON public.order_tracking;

CREATE POLICY "Owners view own order tracking"
    ON public.order_tracking FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.orders
            WHERE public.orders.id = public.order_tracking.order_id
              AND (public.orders.customer_id = auth.uid() OR public.orders.email = auth.email())
        )
    );

-- 4. product_collections: merchandising writes are admin-only
--    (public SELECT from 01 and the admin FOR ALL policy from 10 remain)
DROP POLICY IF EXISTS "Allow public insert on product_collections" ON public.product_collections;
DROP POLICY IF EXISTS "Allow public delete on product_collections" ON public.product_collections;

-- 5. customers: replace the FOR ALL self-service policy with column-safe ones.
--    WITH CHECK (is_admin = FALSE) blocks a non-admin from flipping their own
--    flag; real admins are covered by "Admin full access on customers" (10).
DROP POLICY IF EXISTS "Users read/write own profile" ON public.customers;

CREATE POLICY "Users view own profile"
    ON public.customers FOR SELECT TO authenticated
    USING (auth.uid() = id);

CREATE POLICY "Users update own profile"
    ON public.customers FOR UPDATE TO authenticated
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id AND is_admin = FALSE);


-- ─────────────────────────────────────────────────────────────────────────
-- 40_order_integrity.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Migration 40: Server-authoritative ordering (COD), sequence-backed order IDs,
--               inventory decrement, discount redemption, guarded cart capture
-- ════════════════════════════════════════════════════════════════════════════════
-- The storefront previously computed order IDs (4-digit random on a PK) and all
-- prices client-side, decremented no stock, and never redeemed discounts. This
-- migration moves the trusted path into SECURITY DEFINER functions that the app
-- calls from server route handlers (see /api/checkout, /api/abandoned-cart,
-- /api/track). Payment is cash-on-delivery only for now (owner decision); the
-- payment_* columns exist so a gateway can be added later without reshaping data.

-- 1. Payment / discount columns on orders
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(30) DEFAULT 'cod';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30) DEFAULT 'pending_collection';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_ref VARCHAR(255);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount_code VARCHAR(100);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10, 2) DEFAULT 0.00;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_fee DECIMAL(10, 2) DEFAULT 0.00;

-- 2. Human-readable sequential order numbers (replaces ORD-<4-digit-random>)
CREATE SEQUENCE IF NOT EXISTS public.order_number_seq START WITH 10001;

-- 3. place_order: the only write path for storefront orders.
--    Re-prices every line from public.products, validates and decrements stock,
--    applies a discount code atomically, and writes orders + order_items +
--    order_tracking in one transaction. Returns the totals the server computed.
CREATE OR REPLACE FUNCTION public.place_order(
    p_email TEXT,
    p_first_name TEXT,
    p_last_name TEXT,
    p_phone TEXT,
    p_shipping JSONB,
    p_items JSONB,
    p_discount_code TEXT DEFAULT NULL,
    p_abandoned_cart_id UUID DEFAULT NULL,
    p_currency TEXT DEFAULT 'AED',
    p_exchange_rate NUMERIC DEFAULT 1
) RETURNS JSONB AS $$
DECLARE
    v_order_id TEXT;
    v_item JSONB;
    v_product public.products%ROWTYPE;
    v_qty INT;
    v_size TEXT;
    v_stock INT;
    v_subtotal NUMERIC(10,2) := 0;
    v_shipping_fee NUMERIC(10,2) := 0;
    v_discount public.discounts%ROWTYPE;
    v_discount_amount NUMERIC(10,2) := 0;
    v_total NUMERIC(10,2);
    v_free_shipping_threshold CONSTANT NUMERIC := 250;
    v_flat_shipping_fee CONSTANT NUMERIC := 25;
    v_line_count INT;
BEGIN
    -- Input validation
    IF p_email IS NULL OR p_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' OR length(p_email) > 255 THEN
        RAISE EXCEPTION 'invalid_email';
    END IF;
    IF p_shipping IS NULL OR jsonb_typeof(p_shipping) <> 'object' THEN
        RAISE EXCEPTION 'invalid_shipping_address';
    END IF;
    IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' THEN
        RAISE EXCEPTION 'invalid_items';
    END IF;
    v_line_count := jsonb_array_length(p_items);
    IF v_line_count < 1 OR v_line_count > 50 THEN
        RAISE EXCEPTION 'invalid_items';
    END IF;
    IF p_currency IS NULL OR p_currency !~ '^[A-Z]{3}$' THEN
        RAISE EXCEPTION 'invalid_currency';
    END IF;
    IF p_exchange_rate IS NULL OR p_exchange_rate <= 0 OR p_exchange_rate > 1000 THEN
        RAISE EXCEPTION 'invalid_exchange_rate';
    END IF;

    -- Price and stock-check every line from the catalogue (never trust the client)
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
        v_qty := COALESCE((v_item->>'quantity')::INT, 0);
        v_size := COALESCE(v_item->>'size', '');
        IF v_qty < 1 OR v_qty > 20 THEN
            RAISE EXCEPTION 'invalid_quantity';
        END IF;

        SELECT * INTO v_product FROM public.products WHERE id = (v_item->>'product_id')::INT;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'unknown_product:%', v_item->>'product_id';
        END IF;
        IF v_product.sizes IS NOT NULL AND array_length(v_product.sizes, 1) > 0
           AND NOT (v_size = ANY(v_product.sizes)) THEN
            RAISE EXCEPTION 'invalid_size:%', v_product.name;
        END IF;

        -- Lock the inventory row; missing rows are treated as not stock-tracked
        SELECT stock_level INTO v_stock FROM public.inventory
        WHERE product_id = v_product.id AND size = v_size
        FOR UPDATE;
        IF FOUND THEN
            IF v_stock < v_qty THEN
                RAISE EXCEPTION 'out_of_stock:%', v_product.name;
            END IF;
            UPDATE public.inventory SET stock_level = stock_level - v_qty
            WHERE product_id = v_product.id AND size = v_size;
        END IF;

        v_subtotal := v_subtotal + (v_product.price * v_qty);
    END LOOP;

    IF v_subtotal < v_free_shipping_threshold THEN
        v_shipping_fee := v_flat_shipping_fee;
    END IF;

    -- Discount redemption (atomic: row locked, usage counted here only)
    IF p_discount_code IS NOT NULL AND length(trim(p_discount_code)) > 0 THEN
        SELECT * INTO v_discount FROM public.discounts
        WHERE upper(code) = upper(trim(p_discount_code))
          AND is_active = TRUE
          AND (starts_at IS NULL OR starts_at <= CURRENT_TIMESTAMP)
          AND (ends_at IS NULL OR ends_at >= CURRENT_TIMESTAMP)
        FOR UPDATE;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'invalid_discount_code';
        END IF;
        IF v_discount.usage_limit IS NOT NULL AND v_discount.usage_count >= v_discount.usage_limit THEN
            RAISE EXCEPTION 'discount_exhausted';
        END IF;
        IF v_subtotal < COALESCE(v_discount.min_requirement, 0) THEN
            RAISE EXCEPTION 'discount_minimum_not_met:%', v_discount.min_requirement;
        END IF;
        IF v_discount.type = 'percentage' THEN
            v_discount_amount := round(v_subtotal * v_discount.value / 100, 2);
        ELSE
            v_discount_amount := LEAST(v_discount.value, v_subtotal);
        END IF;
        UPDATE public.discounts SET usage_count = usage_count + 1 WHERE id = v_discount.id;
    END IF;

    v_total := GREATEST(v_subtotal - v_discount_amount, 0) + v_shipping_fee;
    v_order_id := 'ORD-' || nextval('public.order_number_seq')::TEXT;

    INSERT INTO public.orders (
        id, customer_id, email, total_price, status, shipping_address,
        currency, exchange_rate, converted_total,
        payment_method, payment_status, discount_code, discount_amount, shipping_fee
    ) VALUES (
        v_order_id, auth.uid(), lower(p_email), v_total, 'processing', p_shipping,
        p_currency, p_exchange_rate, round(v_total * p_exchange_rate, 2)::TEXT || ' ' || p_currency,
        'cod', 'pending_collection',
        CASE WHEN v_discount_amount > 0 THEN upper(trim(p_discount_code)) END,
        v_discount_amount, v_shipping_fee
    );

    INSERT INTO public.order_items (order_id, product_id, size, quantity, unit_price)
    SELECT v_order_id,
           (item->>'product_id')::INT,
           item->>'size',
           (item->>'quantity')::INT,
           p.price
    FROM jsonb_array_elements(p_items) AS item
    JOIN public.products p ON p.id = (item->>'product_id')::INT;

    INSERT INTO public.order_tracking (order_id, status, location, description)
    VALUES (v_order_id, 'Order Placed', 'Dubai Headquarters',
            'We have received your order. Payment is collected on delivery.');

    -- Convert the shopper's abandoned cart (email-guarded)
    IF p_abandoned_cart_id IS NOT NULL THEN
        UPDATE public.abandoned_carts
        SET converted = TRUE, converted_order_id = v_order_id, updated_at = CURRENT_TIMESTAMP
        WHERE id = p_abandoned_cart_id AND lower(email) = lower(p_email);
    END IF;

    RETURN jsonb_build_object(
        'order_id', v_order_id,
        'subtotal', v_subtotal,
        'shipping_fee', v_shipping_fee,
        'discount_amount', v_discount_amount,
        'total', v_total,
        'currency', p_currency
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- 4. capture_abandoned_cart: PII-safe upsert used by the checkout autosave.
--    Existing rows can only be updated by a caller supplying the same email,
--    and the table itself is no longer readable anonymously (migration 39).
CREATE OR REPLACE FUNCTION public.capture_abandoned_cart(
    p_id UUID,
    p_email TEXT,
    p_first_name TEXT,
    p_last_name TEXT,
    p_phone TEXT,
    p_shipping JSONB,
    p_cart_items JSONB,
    p_total NUMERIC,
    p_currency TEXT DEFAULT 'AED',
    p_exchange_rate NUMERIC DEFAULT 1
) RETURNS UUID AS $$
BEGIN
    IF p_id IS NULL OR p_email IS NULL OR p_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' OR length(p_email) > 255 THEN
        RAISE EXCEPTION 'invalid_input';
    END IF;
    IF p_cart_items IS NOT NULL AND (jsonb_typeof(p_cart_items) <> 'array' OR jsonb_array_length(p_cart_items) > 50) THEN
        RAISE EXCEPTION 'invalid_input';
    END IF;

    INSERT INTO public.abandoned_carts (
        id, email, first_name, last_name, phone, shipping_address, cart_items,
        total_price, currency, exchange_rate, converted
    ) VALUES (
        p_id, lower(p_email), left(p_first_name, 255), left(p_last_name, 255), left(p_phone, 50),
        p_shipping, p_cart_items, COALESCE(p_total, 0), p_currency, p_exchange_rate, FALSE
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        first_name = EXCLUDED.first_name,
        last_name = EXCLUDED.last_name,
        phone = EXCLUDED.phone,
        shipping_address = EXCLUDED.shipping_address,
        cart_items = EXCLUDED.cart_items,
        total_price = EXCLUDED.total_price,
        currency = EXCLUDED.currency,
        exchange_rate = EXCLUDED.exchange_rate,
        updated_at = CURRENT_TIMESTAMP
    WHERE lower(public.abandoned_carts.email) = lower(EXCLUDED.email)
      AND public.abandoned_carts.converted = FALSE;

    RETURN p_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- 5. track_guest_order: order status + tracking timeline for guests, gated on
--    knowing both the order number and the order email (order_tracking is no
--    longer world-readable after migration 39).
CREATE OR REPLACE FUNCTION public.track_guest_order(
    p_order_id TEXT,
    p_email TEXT
) RETURNS JSONB AS $$
DECLARE
    v_order public.orders%ROWTYPE;
    v_tracking JSONB;
BEGIN
    SELECT * INTO v_order FROM public.orders
    WHERE id = p_order_id AND lower(email) = lower(COALESCE(p_email, ''));
    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'status', t.status,
        'location', t.location,
        'description', t.description,
        'updated_at', t.updated_at
    ) ORDER BY t.updated_at), '[]'::jsonb)
    INTO v_tracking
    FROM public.order_tracking t WHERE t.order_id = v_order.id;

    RETURN jsonb_build_object(
        'order_id', v_order.id,
        'status', v_order.status,
        'total_price', v_order.total_price,
        'created_at', v_order.created_at,
        'tracking_number', v_order.tracking_number,
        'tracking_url', v_order.tracking_url,
        'tracking', v_tracking
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- 6. Execution grants: these functions are the public API surface
REVOKE ALL ON FUNCTION public.place_order(TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, TEXT, UUID, TEXT, NUMERIC) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.capture_abandoned_cart(UUID, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, NUMERIC, TEXT, NUMERIC) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.track_guest_order(TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.place_order(TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, TEXT, UUID, TEXT, NUMERIC) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.capture_abandoned_cart(UUID, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, NUMERIC, TEXT, NUMERIC) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.track_guest_order(TEXT, TEXT) TO anon, authenticated;


-- ─────────────────────────────────────────────────────────────────────────
-- 41_newsletter_subscribers.sql
-- ─────────────────────────────────────────────────────────────────────────

-- Migration 41: Newsletter subscribers (the footer forms previously discarded emails)
-- ════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    source VARCHAR(50) DEFAULT 'footer',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- Admins can read/manage the list; the public writes only through the function below
CREATE POLICY "Admin access on newsletter_subscribers"
    ON public.newsletter_subscribers FOR ALL TO authenticated
    USING (public.is_admin(auth.uid()));

CREATE OR REPLACE FUNCTION public.subscribe_newsletter(p_email TEXT, p_source TEXT DEFAULT 'footer')
RETURNS BOOLEAN AS $$
BEGIN
    IF p_email IS NULL OR p_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' OR length(p_email) > 255 THEN
        RETURN FALSE;
    END IF;
    INSERT INTO public.newsletter_subscribers (email, source)
    VALUES (lower(trim(p_email)), left(COALESCE(p_source, 'footer'), 50))
    ON CONFLICT (email) DO NOTHING;
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

REVOKE ALL ON FUNCTION public.subscribe_newsletter(TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.subscribe_newsletter(TEXT, TEXT) TO anon, authenticated;


-- ─────────────────────────────────────────────────────────────────────────
-- 42_order_lifecycle_and_provisioning.sql
-- ─────────────────────────────────────────────────────────────────────────

-- ============================================================================
-- 42. Order lifecycle, customer provisioning and the payment seam
--
-- Follows 38–41. Fixes three defects found while hardening the release:
--
--   1. handle_new_user() used ON CONFLICT (email) DO NOTHING, so if a row
--      already held the signup email (e.g. the seeded admin@gharib.com) the new
--      auth user never received a customers row. is_admin(auth.uid()) then
--      returned FALSE forever and every owner-scoped RLS policy failed shut.
--      The account was silently orphaned — including the account the rollout
--      guide tells the owner to promote.
--
--   2. place_order() never maintained customers.total_spent / orders_count, and
--      no trigger did either, so the admin customer registry showed 0 for every
--      real order.
--
--   3. The order status vocabulary disagreed across the stack. place_order wrote
--      'processing', which the admin dropdown did not offer; the customer
--      stepper only understood 'shipped'/'delivered', so an order marked
--      'out_for_delivery' still displayed as freshly placed. The canonical list
--      now lives in src/app/lib/orders.ts and is mirrored here.
--
-- Also makes the payment seam real: place_order accepts the method and the
-- provider-declared payment status, validated here against an allowlist so a
-- client cannot claim an order is paid.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Customer provisioning that cannot orphan an account
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    v_first_name VARCHAR(255) := '';
    v_last_name VARCHAR(255) := '';
    v_phone VARCHAR(50) := '';
    v_conflict_id UUID;
BEGIN
    IF new.email IS NULL THEN
        RETURN new;
    END IF;

    IF new.raw_user_meta_data IS NOT NULL THEN
        v_first_name := COALESCE(new.raw_user_meta_data->>'first_name', '');
        v_last_name  := COALESCE(new.raw_user_meta_data->>'last_name', '');
        v_phone      := COALESCE(new.raw_user_meta_data->>'phone', '');
    END IF;

    -- Already provisioned (e.g. trigger re-fired) — nothing to do.
    IF EXISTS (SELECT 1 FROM public.customers WHERE id = new.id) THEN
        RETURN new;
    END IF;

    -- Does a row already hold this email under a different id?
    SELECT id INTO v_conflict_id
    FROM public.customers
    WHERE lower(email) = lower(new.email)
    LIMIT 1;

    IF v_conflict_id IS NOT NULL THEN
        IF EXISTS (SELECT 1 FROM auth.users WHERE id = v_conflict_id) THEN
            -- A live account already owns this email. auth.users.email is
            -- unique, so this should be unreachable; fail loudly rather than
            -- silently leaving the new user without a profile.
            RAISE EXCEPTION 'customer_email_conflict:%', new.email;
        END IF;

        -- Orphan/seed row (no matching auth user). Remove it so the real
        -- account can take the email. Note this deliberately does NOT carry
        -- over is_admin: inheriting a seeded admin flag by signing up with its
        -- email is exactly the hijack migration 38 closed.
        DELETE FROM public.customers WHERE id = v_conflict_id;
    END IF;

    INSERT INTO public.customers (
        id, first_name, last_name, email, phone, note,
        total_spent, orders_count, is_admin
    )
    VALUES (
        new.id, v_first_name, v_last_name, new.email, v_phone,
        'Auto-registered Privé Member.', 0.00, 0, FALSE
    )
    ON CONFLICT (id) DO NOTHING;

    -- Link historical guest orders for this email to the new account. The
    -- orders SELECT policy already grants access by email = auth.email(), so
    -- this adds no visibility the email-based policy does not already grant.
    UPDATE public.orders SET customer_id = new.id
    WHERE email = new.email AND customer_id IS NULL;

    -- Adopt the spend history those orders represent.
    UPDATE public.customers c
    SET total_spent = COALESCE(agg.spent, 0),
        orders_count = COALESCE(agg.cnt, 0)
    FROM (
        SELECT COALESCE(SUM(total_price), 0) AS spent, COUNT(*) AS cnt
        FROM public.orders
        WHERE customer_id = new.id AND status <> 'cancelled'
    ) agg
    WHERE c.id = new.id;

    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- ---------------------------------------------------------------------------
-- 2. Canonical order status vocabulary
-- ---------------------------------------------------------------------------

-- Orders created by the previous place_order() used a status the admin panel
-- could not display or set. Move them onto the canonical initial status.
UPDATE public.orders SET status = 'pending' WHERE status = 'processing';

-- ---------------------------------------------------------------------------
-- 3. place_order: payment seam + customer spend rollup + canonical status
--
-- The parameter list changes, so the previous signature is dropped rather than
-- replaced (CREATE OR REPLACE cannot add parameters).
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.place_order(
    TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, TEXT, UUID, TEXT, NUMERIC
);

CREATE OR REPLACE FUNCTION public.place_order(
    p_email TEXT,
    p_first_name TEXT,
    p_last_name TEXT,
    p_phone TEXT,
    p_shipping JSONB,
    p_items JSONB,
    p_discount_code TEXT DEFAULT NULL,
    p_abandoned_cart_id UUID DEFAULT NULL,
    p_currency TEXT DEFAULT 'AED',
    p_exchange_rate NUMERIC DEFAULT 1,
    p_payment_method TEXT DEFAULT 'cod',
    p_payment_status TEXT DEFAULT 'pending_collection'
) RETURNS JSONB AS $$
DECLARE
    v_order_id TEXT;
    v_item JSONB;
    v_product public.products%ROWTYPE;
    v_qty INT;
    v_size TEXT;
    v_stock INT;
    v_subtotal NUMERIC(10,2) := 0;
    v_shipping_fee NUMERIC(10,2) := 0;
    v_discount public.discounts%ROWTYPE;
    v_discount_amount NUMERIC(10,2) := 0;
    v_total NUMERIC(10,2);
    v_free_shipping_threshold CONSTANT NUMERIC := 250;
    v_flat_shipping_fee CONSTANT NUMERIC := 25;
    v_line_count INT;
    v_customer_id UUID := auth.uid();
BEGIN
    -- Input validation
    IF p_email IS NULL OR p_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' OR length(p_email) > 255 THEN
        RAISE EXCEPTION 'invalid_email';
    END IF;
    IF p_shipping IS NULL OR jsonb_typeof(p_shipping) <> 'object' THEN
        RAISE EXCEPTION 'invalid_shipping_address';
    END IF;
    IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' THEN
        RAISE EXCEPTION 'invalid_items';
    END IF;
    v_line_count := jsonb_array_length(p_items);
    IF v_line_count < 1 OR v_line_count > 50 THEN
        RAISE EXCEPTION 'invalid_items';
    END IF;
    IF p_currency IS NULL OR p_currency !~ '^[A-Z]{3}$' THEN
        RAISE EXCEPTION 'invalid_currency';
    END IF;
    IF p_exchange_rate IS NULL OR p_exchange_rate <= 0 OR p_exchange_rate > 1000 THEN
        RAISE EXCEPTION 'invalid_exchange_rate';
    END IF;

    -- Payment seam. The client names a method; the pairing of method to an
    -- initial payment status is fixed HERE so a caller cannot declare an order
    -- paid. A future gateway adds its own allowed pair alongside this one.
    IF NOT (p_payment_method = 'cod' AND p_payment_status = 'pending_collection') THEN
        RAISE EXCEPTION 'unsupported_payment_method';
    END IF;

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_qty := COALESCE((v_item->>'quantity')::INT, 0);
        v_size := COALESCE(v_item->>'size', '');
        IF v_qty < 1 OR v_qty > 20 THEN
            RAISE EXCEPTION 'invalid_quantity';
        END IF;

        SELECT * INTO v_product FROM public.products
        WHERE id = (v_item->>'product_id')::INT;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'unknown_product:%', v_item->>'product_id';
        END IF;
        IF v_product.sizes IS NOT NULL AND array_length(v_product.sizes, 1) > 0
           AND NOT (v_size = ANY(v_product.sizes)) THEN
            RAISE EXCEPTION 'invalid_size:%', v_product.name;
        END IF;

        -- Lock the inventory row; missing rows are treated as not stock-tracked.
        -- See the operations note at the foot of this file.
        SELECT stock_level INTO v_stock FROM public.inventory
        WHERE product_id = v_product.id AND size = v_size
        FOR UPDATE;
        IF FOUND THEN
            IF v_stock < v_qty THEN
                RAISE EXCEPTION 'out_of_stock:%', v_product.name;
            END IF;
            UPDATE public.inventory SET stock_level = stock_level - v_qty
            WHERE product_id = v_product.id AND size = v_size;
        END IF;

        v_subtotal := v_subtotal + (v_product.price * v_qty);
    END LOOP;

    IF v_subtotal < v_free_shipping_threshold THEN
        v_shipping_fee := v_flat_shipping_fee;
    END IF;

    -- Discount redemption (atomic: row locked, usage counted here only)
    IF p_discount_code IS NOT NULL AND length(trim(p_discount_code)) > 0 THEN
        SELECT * INTO v_discount FROM public.discounts
        WHERE upper(code) = upper(trim(p_discount_code))
          AND is_active = TRUE
          AND (starts_at IS NULL OR starts_at <= CURRENT_TIMESTAMP)
          AND (ends_at IS NULL OR ends_at >= CURRENT_TIMESTAMP)
        FOR UPDATE;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'invalid_discount_code';
        END IF;
        IF v_discount.usage_limit IS NOT NULL AND v_discount.usage_count >= v_discount.usage_limit THEN
            RAISE EXCEPTION 'discount_exhausted';
        END IF;
        IF v_subtotal < COALESCE(v_discount.min_requirement, 0) THEN
            RAISE EXCEPTION 'discount_minimum_not_met:%', v_discount.min_requirement;
        END IF;
        IF v_discount.type = 'percentage' THEN
            v_discount_amount := round(v_subtotal * v_discount.value / 100, 2);
        ELSE
            v_discount_amount := LEAST(v_discount.value, v_subtotal);
        END IF;
        UPDATE public.discounts SET usage_count = usage_count + 1 WHERE id = v_discount.id;
    END IF;

    v_total := GREATEST(v_subtotal - v_discount_amount, 0) + v_shipping_fee;
    v_order_id := 'ORD-' || nextval('public.order_number_seq')::TEXT;

    INSERT INTO public.orders (
        id, customer_id, email, total_price, status, shipping_address,
        currency, exchange_rate, converted_total,
        payment_method, payment_status, discount_code, discount_amount, shipping_fee
    ) VALUES (
        v_order_id, v_customer_id, lower(p_email), v_total, 'pending', p_shipping,
        p_currency, p_exchange_rate, round(v_total * p_exchange_rate, 2)::TEXT || ' ' || p_currency,
        p_payment_method, p_payment_status,
        CASE WHEN v_discount_amount > 0 THEN upper(trim(p_discount_code)) END,
        v_discount_amount, v_shipping_fee
    );

    INSERT INTO public.order_items (order_id, product_id, size, quantity, unit_price)
    SELECT v_order_id,
           (item->>'product_id')::INT,
           item->>'size',
           (item->>'quantity')::INT,
           p.price
    FROM jsonb_array_elements(p_items) AS item
    JOIN public.products p ON p.id = (item->>'product_id')::INT;

    INSERT INTO public.order_tracking (order_id, status, location, description)
    VALUES (v_order_id, 'Order Placed', 'Dubai Headquarters',
            'We have received your order. Payment is collected on delivery.');

    -- Keep the customer registry truthful (previously never maintained).
    IF v_customer_id IS NOT NULL THEN
        UPDATE public.customers
        SET total_spent = COALESCE(total_spent, 0) + v_total,
            orders_count = COALESCE(orders_count, 0) + 1,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = v_customer_id;
    END IF;

    -- Convert the shopper's abandoned cart (email-guarded)
    IF p_abandoned_cart_id IS NOT NULL THEN
        UPDATE public.abandoned_carts
        SET converted = TRUE, converted_order_id = v_order_id, updated_at = CURRENT_TIMESTAMP
        WHERE id = p_abandoned_cart_id AND lower(email) = lower(p_email);
    END IF;

    RETURN jsonb_build_object(
        'order_id', v_order_id,
        'subtotal', v_subtotal,
        'shipping_fee', v_shipping_fee,
        'discount_amount', v_discount_amount,
        'total', v_total,
        'currency', p_currency,
        'payment_method', p_payment_method,
        'payment_status', p_payment_status
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

REVOKE ALL ON FUNCTION public.place_order(
    TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, TEXT, UUID, TEXT, NUMERIC, TEXT, TEXT
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.place_order(
    TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, TEXT, UUID, TEXT, NUMERIC, TEXT, TEXT
) TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. Backfill the spend rollup for orders placed before this migration
-- ---------------------------------------------------------------------------

UPDATE public.customers c
SET total_spent = COALESCE(agg.spent, 0),
    orders_count = COALESCE(agg.cnt, 0)
FROM (
    SELECT customer_id,
           SUM(total_price) AS spent,
           COUNT(*) AS cnt
    FROM public.orders
    WHERE customer_id IS NOT NULL AND status <> 'cancelled'
    GROUP BY customer_id
) agg
WHERE c.id = agg.customer_id;

-- ---------------------------------------------------------------------------
-- OPERATIONS NOTE — stock tracking
--
-- place_order only enforces stock for (product_id, size) pairs that HAVE an
-- inventory row; a product with no row is treated as not stock-tracked and
-- always sells. Most of the catalogue currently has no inventory rows, so the
-- "inventory is decremented" guarantee applies only to products you have
-- actually stocked in the admin Inventory Tracker.
--
-- This migration deliberately does NOT invent stock levels. When you know your
-- real counts, either enter them in the admin panel, or seed a baseline by
-- running the statement below with a number you choose:
--
--   INSERT INTO public.inventory (product_id, size, stock_level)
--   SELECT p.id, s.size, 0            -- <- replace 0 with your real count
--   FROM public.products p
--   CROSS JOIN LATERAL unnest(COALESCE(p.sizes, ARRAY['50ml'])) AS s(size)
--   ON CONFLICT (product_id, size) DO NOTHING;
--
-- Seeding 0 makes every seeded line refuse to sell until you raise it, which is
-- the safe default if you want hard stock control from day one.
-- ---------------------------------------------------------------------------


-- ─────────────────────────────────────────────────────────────────────────
-- 43_seed_operational_data.sql
-- ─────────────────────────────────────────────────────────────────────────

-- ============================================================================
-- 43. Operational data repair + stock seeding
--
-- Fixes two things found by auditing the live database against the front end:
--
--   1. `order_tracking` holds 8 rows pointing at ORD-9922, ORD-9923 and
--      ORD-2547 — none of which exist in `orders`. They are leftovers from an
--      early seed. They surface as ghost entries in the admin tracking view and
--      would attach themselves to any future order that reuses those ids.
--
--   2. `inventory` is completely empty. `place_order` only enforces stock for
--      (product_id, size) pairs that HAVE a row, so with an empty table every
--      one of the 138 products sells without limit, the admin Inventory tab
--      shows nothing, and "inventory is decremented" is not true of any order.
--
-- The stock figure seeded here is a placeholder so the stock path is wired and
-- demonstrable end to end. Replace it with your real counts in the admin
-- Inventory Tracker before you start selling.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Remove tracking rows whose order no longer exists
-- ---------------------------------------------------------------------------

DELETE FROM public.order_tracking t
WHERE NOT EXISTS (
    SELECT 1 FROM public.orders o WHERE o.id = t.order_id
);

-- Stop it happening again. The column was declared with a REFERENCES clause in
-- migration 03, but the orphans prove the constraint is not actually present on
-- this database — add it if it is missing.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'order_tracking_order_id_fkey'
          AND conrelid = 'public.order_tracking'::regclass
    ) THEN
        ALTER TABLE public.order_tracking
            ADD CONSTRAINT order_tracking_order_id_fkey
            FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Give every catalogue line a stock row
--
-- One row per (product, size) using each product's own `sizes` array, so the
-- size a shopper picks on the product page is the size that gets decremented.
-- ---------------------------------------------------------------------------

INSERT INTO public.inventory (product_id, size, stock_level, low_stock_threshold)
SELECT p.id, s.size, 25, 5
FROM public.products p
CROSS JOIN LATERAL unnest(
    CASE
        WHEN p.sizes IS NULL OR array_length(p.sizes, 1) IS NULL THEN ARRAY['50ml']
        ELSE p.sizes
    END
) AS s(size)
ON CONFLICT (product_id, size) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Verification (run after applying):
--
--   SELECT count(*) FROM public.inventory;            -- expect ~1 per product-size
--   SELECT count(*) FROM public.order_tracking t
--     WHERE NOT EXISTS (SELECT 1 FROM public.orders o WHERE o.id = t.order_id);
--                                                     -- expect 0
-- ---------------------------------------------------------------------------

