#!/usr/bin/env bash
# Regenerates scripts/apply-migrations-38-43.sql from the numbered migrations.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=scripts/apply-migrations-38-43.sql
{
  echo "-- ==========================================================================="
  echo "-- GENERATED BUNDLE — migrations 38 → 43, concatenated in order."
  echo "--"
  echo "-- Paste this whole file into the Supabase SQL editor and run it once."
  echo "-- It is safe to re-run: every statement is idempotent or guarded."
  echo "--"
  echo "-- Regenerate with:  bash scripts/build-migration-bundle.sh"
  echo "-- Source of truth remains supabase/migrations/*.sql — do not edit this file."
  echo "-- ==========================================================================="
  echo
  for f in supabase/migrations/3[89]_*.sql supabase/migrations/4[0-3]_*.sql; do
    echo
    echo "-- ─────────────────────────────────────────────────────────────────────────"
    echo "-- $(basename "$f")"
    echo "-- ─────────────────────────────────────────────────────────────────────────"
    echo
    cat "$f"
    echo
  done
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
