-- Migration 25: Seed the Rasasi catalogue
-- ══════════════════════════════════════════════════════════════════════════════════════════
-- Products seed at the placeholder price of AED 199.00 with the shared placeholder bottle
-- image (/placeholder-bottle.png); real prices and photography are set from the admin panel.
--
-- Re-running this file is safe: every statement is ON CONFLICT DO NOTHING, so uploaded
-- images, edited prices and adjusted stock levels are never overwritten.

-- 1. Products
INSERT INTO public.products
    (id, brand, name, price, sizes, image_url, image_urls, description, tagline,
     olfactory_group, tags, is_new, is_bestseller, is_featured_large)
VALUES
    (1000, 'RASASI', 'Hawas Ice', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Ice is an icy citrus-marine eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'hawas', 'men', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1001, 'RASASI', 'Hawas Men', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Men is a fruity-aquatic eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'hawas', 'men', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1002, 'RASASI', 'Hawas For Her', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas For Her is a luminous fruity-floral eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Floral & Sweet', ARRAY['rasasi', 'hawas', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1003, 'RASASI', 'Hawas Diva', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Diva is an opulent floral eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Floral & Sweet', ARRAY['rasasi', 'hawas', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1004, 'RASASI', 'Hawas Malibu', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Malibu is a sun-warmed coastal eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'hawas', 'unisex', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1005, 'RASASI', 'Hawas Kobra', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Kobra is a dark woody-spiced eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Woody & Oud', ARRAY['rasasi', 'hawas', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1006, 'RASASI', 'Hawas Chrome', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Chrome is a metallic-fresh eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'hawas', 'men', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1007, 'RASASI', 'Hawas Majestic', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Majestic is a regal amber eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Amber & Oriental', ARRAY['rasasi', 'hawas', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1008, 'RASASI', 'Hawas Eclat', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Eclat is a sparkling floral eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Floral & Sweet', ARRAY['rasasi', 'hawas', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1009, 'RASASI', 'Hawas Fire', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Fire is a smouldering spiced eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Amber & Oriental', ARRAY['rasasi', 'hawas', 'men', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1010, 'RASASI', 'Hawas Atlantis', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Atlantis is a deep marine eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'hawas', 'men', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1011, 'RASASI', 'Hawas Viper', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Viper is a sharp woody-leather eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Woody & Oud', ARRAY['rasasi', 'hawas', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1012, 'RASASI', 'Hawas Sapphire', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Sapphire is a crystalline fresh eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'hawas', 'unisex', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1013, 'RASASI', 'Hawas Thunder', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Thunder is a stormy woody eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Woody & Oud', ARRAY['rasasi', 'hawas', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1014, 'RASASI', 'Hawas Pink', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Pink is a soft berry-floral eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Floral & Sweet', ARRAY['rasasi', 'hawas', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1015, 'RASASI', 'Hawas Exotic', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Exotic is a spiced oriental eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Amber & Oriental', ARRAY['rasasi', 'hawas', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1016, 'RASASI', 'Hawas Highness', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Highness is a stately amber-wood eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Amber & Oriental', ARRAY['rasasi', 'hawas', 'men', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1017, 'RASASI', 'Hawas Lava Gold', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Lava Gold is a molten amber eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Amber & Oriental', ARRAY['rasasi', 'hawas', 'men', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1018, 'RASASI', 'Hawas Overdose', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Overdose is an intense sweet-oriental eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Amber & Oriental', ARRAY['rasasi', 'hawas', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1019, 'RASASI', 'Hawas Nautilus', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Nautilus is a salt-air aquatic eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'hawas', 'men', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1020, 'RASASI', 'Hawas London', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas London is a refined smoky-woody eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Woody & Oud', ARRAY['rasasi', 'hawas', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1021, 'RASASI', 'Hawas Tropical', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Tropical is a juicy tropical eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'hawas', 'unisex', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1022, 'RASASI', 'Hawas Verde', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Verde is a green aromatic eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'hawas', 'unisex', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1023, 'RASASI', 'Hawas Reina', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Reina is a regal floral eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Floral & Sweet', ARRAY['rasasi', 'hawas', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1024, 'RASASI', 'Hawas Addiction', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Addiction is an addictive gourmand-floral eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Floral & Sweet', ARRAY['rasasi', 'hawas', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1025, 'RASASI', 'Hawas La''meir', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas La''meir is an oceanic mineral eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'hawas', 'unisex', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1026, 'RASASI', 'Hawas Gold Digger', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Gold Digger is a golden amber-vanilla eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Amber & Oriental', ARRAY['rasasi', 'hawas', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1027, 'RASASI', 'Hawas Elixir', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Elixir is a concentrated amber elixir eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Amber & Oriental', ARRAY['rasasi', 'hawas', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1028, 'RASASI', 'Hawas Black', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hawas Black is a dark woody-oud eau de parfum from the Hawas line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hawas Collection', 'Woody & Oud', ARRAY['rasasi', 'hawas', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1030, 'RASASI', 'Blue For Men', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Blue For Men is a crisp aromatic-fresh eau de parfum from the Rasasi Blue line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Rasasi Blue Collection', 'Fresh & Aquatic', ARRAY['rasasi', 'rasasi-blue', 'men', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1031, 'RASASI', 'Blue For Lady', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Blue For Lady is an airy floral eau de parfum from the Rasasi Blue line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Rasasi Blue Collection', 'Floral & Sweet', ARRAY['rasasi', 'rasasi-blue', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1032, 'RASASI', 'La Yuqawam', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'La Yuqawam is a rich woody-fruity eau de parfum from the Rasasi house. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Rasasi Signature', 'Woody & Oud', ARRAY['rasasi', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1033, 'RASASI', 'Dareej Men', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Dareej Men is a spiced woody eau de parfum from the Dareej line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Dareej Collection', 'Woody & Oud', ARRAY['rasasi', 'dareej', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1034, 'RASASI', 'Dareej Extrait', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Dareej Extrait is a concentrated amber eau de parfum from the Dareej line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Dareej Collection', 'Amber & Oriental', ARRAY['rasasi', 'dareej', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1035, 'RASASI', 'Dareej Women', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Dareej Women is an elegant floral eau de parfum from the Dareej line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Dareej Collection', 'Floral & Sweet', ARRAY['rasasi', 'dareej', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1036, 'RASASI', 'Dareej Passione', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Dareej Passione is a warm floral-gourmand eau de parfum from the Dareej line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Dareej Collection', 'Floral & Sweet', ARRAY['rasasi', 'dareej', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1037, 'RASASI', 'Dareej Magnetic', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Dareej Magnetic is a magnetic woody-spiced eau de parfum from the Dareej line by Rasasi. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Dareej Collection', 'Woody & Oud', ARRAY['rasasi', 'dareej', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE)
ON CONFLICT (id) DO NOTHING;

-- 2. Inventory — one stock row per product/size so the storefront can sell them
INSERT INTO public.inventory (product_id, size, stock_level, low_stock_threshold)
SELECT p.id, s, 25, 5
FROM public.products p, unnest(p.sizes) AS s
WHERE p.id BETWEEN 1000 AND 1037
ON CONFLICT (product_id, size) DO NOTHING;

-- 3. Map every product into the Rasasi brand collection
INSERT INTO public.product_collections (product_id, collection_id)
SELECT id, 'rasasi' FROM public.products WHERE id BETWEEN 1000 AND 1037
ON CONFLICT DO NOTHING;

-- 4. Map products into their sub-line collections
INSERT INTO public.product_collections (product_id, collection_id)
SELECT p.id, l.collection_id
FROM public.products p
JOIN (VALUES
    ('dareej', ARRAY[1033, 1034, 1035, 1036, 1037]),
    ('hawas', ARRAY[1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028]),
    ('rasasi-blue', ARRAY[1030, 1031])
) AS l(collection_id, product_ids) ON p.id = ANY(l.product_ids)
ON CONFLICT DO NOTHING;
