-- Migration 26: Seed the Lattafa catalogue
-- ══════════════════════════════════════════════════════════════════════════════════════════
-- Products seed at the placeholder price of AED 199.00 with the shared placeholder bottle
-- image (/placeholder-bottle.png); real prices and photography are set from the admin panel.
--
-- Re-running this file is safe: every statement is ON CONFLICT DO NOTHING, so uploaded
-- images, edited prices and adjusted stock levels are never overwritten.

-- 1. Products
INSERT INTO public.products
    (id, brand, name, price, sizes, image_url, image_urls, description, tagline,
     olfactory_group, tags, is_new, is_bestseller, is_featured_large)
VALUES
    (1100, 'LATTAFA', 'Khamrah', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Khamrah is a spiced boozy-vanilla eau de parfum from the Khamrah line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Khamrah Collection', 'Amber & Oriental', ARRAY['lattafa', 'khamrah', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1101, 'LATTAFA', 'Khamrah Qahwa', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Khamrah Qahwa is a coffee-spiced eau de parfum from the Khamrah line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Khamrah Collection', 'Amber & Oriental', ARRAY['lattafa', 'khamrah', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1102, 'LATTAFA', 'Khamrah Dukhan', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Khamrah Dukhan is a smoky spiced eau de parfum from the Khamrah line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Khamrah Collection', 'Amber & Oriental', ARRAY['lattafa', 'khamrah', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1103, 'LATTAFA', 'Yara Pink', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Yara Pink is a creamy fruity-floral eau de parfum from the Yara line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Yara Collection', 'Floral & Sweet', ARRAY['lattafa', 'yara', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1104, 'LATTAFA', 'Yara Candy', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Yara Candy is a sugared gourmand eau de parfum from the Yara line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Yara Collection', 'Floral & Sweet', ARRAY['lattafa', 'yara', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1105, 'LATTAFA', 'Yara Tous', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Yara Tous is a soft powdery-floral eau de parfum from the Yara line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Yara Collection', 'Floral & Sweet', ARRAY['lattafa', 'yara', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1106, 'LATTAFA', 'Yara Moi', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Yara Moi is a vanilla-floral eau de parfum from the Yara line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Yara Collection', 'Floral & Sweet', ARRAY['lattafa', 'yara', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1107, 'LATTAFA', 'Asad Black', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Asad Black is a dark woody eau de parfum from the Asad line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Asad Collection', 'Woody & Oud', ARRAY['lattafa', 'asad', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1108, 'LATTAFA', 'Asad Bourbon', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Asad Bourbon is a boozy woody-vanilla eau de parfum from the Asad line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Asad Collection', 'Woody & Oud', ARRAY['lattafa', 'asad', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1109, 'LATTAFA', 'Asad Zanzibar', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Asad Zanzibar is a spiced woody eau de parfum from the Asad line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Asad Collection', 'Woody & Oud', ARRAY['lattafa', 'asad', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1110, 'LATTAFA', 'Bade''e Al Oud Black', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Bade''e Al Oud Black is a deep oud eau de parfum from the Bade''e Al Oud line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Bade''e Al Oud Collection', 'Woody & Oud', ARRAY['lattafa', 'badee-al-oud', 'unisex', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1111, 'LATTAFA', 'Bade''e Al Oud White', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Bade''e Al Oud White is a clean musky-oud eau de parfum from the Bade''e Al Oud line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Bade''e Al Oud Collection', 'Woody & Oud', ARRAY['lattafa', 'badee-al-oud', 'unisex', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1112, 'LATTAFA', 'Bade''e Al Oud Red', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Bade''e Al Oud Red is a rose-oud eau de parfum from the Bade''e Al Oud line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Bade''e Al Oud Collection', 'Woody & Oud', ARRAY['lattafa', 'badee-al-oud', 'unisex', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1113, 'LATTAFA', 'Bade''e Al Oud Purple', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Bade''e Al Oud Purple is a fruity oud eau de parfum from the Bade''e Al Oud line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Bade''e Al Oud Collection', 'Woody & Oud', ARRAY['lattafa', 'badee-al-oud', 'unisex', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1114, 'LATTAFA', 'Bade''e Al Oud Pink', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Bade''e Al Oud Pink is a soft floral-oud eau de parfum from the Bade''e Al Oud line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Bade''e Al Oud Collection', 'Floral & Sweet', ARRAY['lattafa', 'badee-al-oud', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1115, 'LATTAFA', 'Fakhar Lattafa Men', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Fakhar Lattafa Men is a fresh spicy-woody eau de parfum from the Fakhar line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Fakhar Collection', 'Woody & Oud', ARRAY['lattafa', 'fakhar', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1116, 'LATTAFA', 'Fakhar Lattafa Women', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Fakhar Lattafa Women is a fruity floral eau de parfum from the Fakhar line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Fakhar Collection', 'Floral & Sweet', ARRAY['lattafa', 'fakhar', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1117, 'LATTAFA', 'Fakhar Lattafa Gold', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Fakhar Lattafa Gold is a warm amber-gourmand eau de parfum from the Fakhar line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Fakhar Collection', 'Amber & Oriental', ARRAY['lattafa', 'fakhar', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1118, 'LATTAFA', 'Fakhar Lattafa Rose Gold', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Fakhar Lattafa Rose Gold is a rosy gourmand eau de parfum from the Fakhar line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Fakhar Collection', 'Floral & Sweet', ARRAY['lattafa', 'fakhar', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1119, 'LATTAFA', 'Ameerat Al Arab Red', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Ameerat Al Arab Red is a rich oriental eau de parfum from the Ameerat Al Arab line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Ameerat Al Arab Collection', 'Amber & Oriental', ARRAY['lattafa', 'ameerat-al-arab', 'women', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1120, 'LATTAFA', 'Ameerat Al Arab Black', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Ameerat Al Arab Black is a dark oriental eau de parfum from the Ameerat Al Arab line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Ameerat Al Arab Collection', 'Amber & Oriental', ARRAY['lattafa', 'ameerat-al-arab', 'women', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1121, 'LATTAFA', 'Ameerat Al Arab Prive Rose', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Ameerat Al Arab Prive Rose is a rose oriental eau de parfum from the Ameerat Al Arab line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Ameerat Al Arab Collection', 'Floral & Sweet', ARRAY['lattafa', 'ameerat-al-arab', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1122, 'LATTAFA', 'Ana Abiyedh', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Ana Abiyedh is a white musk-floral eau de parfum from the Ana Abiyedh line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Ana Abiyedh Collection', 'Floral & Sweet', ARRAY['lattafa', 'ana-abiyedh', 'unisex', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1123, 'LATTAFA', 'Ana Abiyedh Coral', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Ana Abiyedh Coral is a fruity musk eau de parfum from the Ana Abiyedh line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Ana Abiyedh Collection', 'Floral & Sweet', ARRAY['lattafa', 'ana-abiyedh', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1124, 'LATTAFA', 'Ana Abiyedh Powdery', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Ana Abiyedh Powdery is a powdery musk eau de parfum from the Ana Abiyedh line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Ana Abiyedh Collection', 'Floral & Sweet', ARRAY['lattafa', 'ana-abiyedh', 'unisex', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1125, 'LATTAFA', 'Mayar Pink', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Mayar Pink is a soft fruity-floral eau de parfum from the Mayar line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Mayar Collection', 'Floral & Sweet', ARRAY['lattafa', 'mayar', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1126, 'LATTAFA', 'Mayar Cherry', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Mayar Cherry is a cherry gourmand eau de parfum from the Mayar line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Mayar Collection', 'Floral & Sweet', ARRAY['lattafa', 'mayar', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1127, 'LATTAFA', 'Mayar Natural Intense', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Mayar Natural Intense is an intense floral eau de parfum from the Mayar line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Mayar Collection', 'Floral & Sweet', ARRAY['lattafa', 'mayar', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1128, 'LATTAFA', 'Eclaire', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Eclaire is a creamy gourmand eau de parfum from the Eclaire line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Eclaire Collection', 'Floral & Sweet', ARRAY['lattafa', 'eclaire', 'unisex', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1129, 'LATTAFA', 'Eclaire Banoffee', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Eclaire Banoffee is a banoffee gourmand eau de parfum from the Eclaire line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Eclaire Collection', 'Floral & Sweet', ARRAY['lattafa', 'eclaire', 'unisex', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1130, 'LATTAFA', 'Eclaire Pistachio', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Eclaire Pistachio is a pistachio gourmand eau de parfum from the Eclaire line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Eclaire Collection', 'Floral & Sweet', ARRAY['lattafa', 'eclaire', 'unisex', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1131, 'LATTAFA', 'Ejaazi', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Ejaazi is a sweet amber-oriental eau de parfum from the Lattafa house. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Lattafa Signature', 'Amber & Oriental', ARRAY['lattafa', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1132, 'LATTAFA', 'Atlas', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Atlas is an aromatic woody eau de parfum from the Lattafa house. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Lattafa Signature', 'Woody & Oud', ARRAY['lattafa', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1133, 'LATTAFA', 'Noble Ameer', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Noble Ameer is a regal amber-spice eau de parfum from the Noble line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Noble Collection', 'Amber & Oriental', ARRAY['lattafa', 'noble', 'men', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1134, 'LATTAFA', 'Noble Wazeer', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Noble Wazeer is a refined oriental eau de parfum from the Noble line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Noble Collection', 'Amber & Oriental', ARRAY['lattafa', 'noble', 'men', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1135, 'LATTAFA', 'Mahir Black', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Mahir Black is a dark woody-spiced eau de parfum from the Mahir line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Mahir Collection', 'Woody & Oud', ARRAY['lattafa', 'mahir', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1136, 'LATTAFA', 'Mahir Legacy', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Mahir Legacy is a leathery woody eau de parfum from the Mahir line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Mahir Collection', 'Woody & Oud', ARRAY['lattafa', 'mahir', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1137, 'LATTAFA', 'Mahir Gold', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Mahir Gold is a golden amber-wood eau de parfum from the Mahir line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Mahir Collection', 'Amber & Oriental', ARRAY['lattafa', 'mahir', 'men', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1138, 'LATTAFA', 'His Confession', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'His Confession is a confident woody-aromatic eau de parfum from the Confession line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Confession Collection', 'Woody & Oud', ARRAY['lattafa', 'confession', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1139, 'LATTAFA', 'Her Confession', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Her Confession is a seductive floral eau de parfum from the Confession line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Confession Collection', 'Floral & Sweet', ARRAY['lattafa', 'confession', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1140, 'LATTAFA', 'Afeef', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Afeef is a soft oriental-musk eau de parfum from the Lattafa house. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Lattafa Signature', 'Amber & Oriental', ARRAY['lattafa', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1141, 'LATTAFA', 'Teriaq', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Teriaq is a honeyed amber eau de parfum from the Teriaq line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Teriaq Collection', 'Amber & Oriental', ARRAY['lattafa', 'teriaq', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1142, 'LATTAFA', 'Teriaq Intense', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Teriaq Intense is a deepened amber eau de parfum from the Teriaq line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Teriaq Collection', 'Amber & Oriental', ARRAY['lattafa', 'teriaq', 'unisex', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1143, 'LATTAFA', 'Musammam White Intense', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Musammam White Intense is a creamy woody eau de parfum from the Musammam line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Musammam Collection', 'Woody & Oud', ARRAY['lattafa', 'musammam', 'unisex', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1144, 'LATTAFA', 'Musammam Black Intense', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Musammam Black Intense is a smoky woody eau de parfum from the Musammam line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Musammam Collection', 'Woody & Oud', ARRAY['lattafa', 'musammam', 'unisex', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1145, 'LATTAFA', 'Hayaati Black', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hayaati Black is a dark aromatic-woody eau de parfum from the Hayaati line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hayaati Collection', 'Woody & Oud', ARRAY['lattafa', 'hayaati', 'men', 'wood', 'oud'], FALSE, FALSE, FALSE),
    (1146, 'LATTAFA', 'Hayaati Florence', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hayaati Florence is a lush floral eau de parfum from the Hayaati line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hayaati Collection', 'Floral & Sweet', ARRAY['lattafa', 'hayaati', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE),
    (1147, 'LATTAFA', 'Hayaati Gold Elixir', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hayaati Gold Elixir is an amber elixir eau de parfum from the Hayaati line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hayaati Collection', 'Amber & Oriental', ARRAY['lattafa', 'hayaati', 'men', 'amber', 'oriental'], FALSE, FALSE, FALSE),
    (1148, 'LATTAFA', 'Hayaati Blue', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Hayaati Blue is a fresh aquatic eau de parfum from the Hayaati line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Hayaati Collection', 'Fresh & Aquatic', ARRAY['lattafa', 'hayaati', 'men', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1149, 'LATTAFA', 'Rave Now', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Rave Now is an energetic fresh-spicy eau de parfum from the Rave Now line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Rave Now Collection', 'Fresh & Aquatic', ARRAY['lattafa', 'rave-now', 'men', 'fresh', 'aquatic'], FALSE, FALSE, FALSE),
    (1150, 'LATTAFA', 'Rave Now Women', 199.00, ARRAY['100ml'], '/placeholder-bottle.png', ARRAY['/placeholder-bottle.png']::TEXT[], 'Rave Now Women is a vibrant fruity-floral eau de parfum from the Rave Now line by Lattafa. An extended-wear composition built for the Gulf climate, presented in 100ml.', 'Rave Now Collection', 'Floral & Sweet', ARRAY['lattafa', 'rave-now', 'women', 'floral', 'sweet'], FALSE, FALSE, FALSE)
ON CONFLICT (id) DO NOTHING;

-- 2. Inventory — one stock row per product/size so the storefront can sell them
INSERT INTO public.inventory (product_id, size, stock_level, low_stock_threshold)
SELECT p.id, s, 25, 5
FROM public.products p, unnest(p.sizes) AS s
WHERE p.id BETWEEN 1100 AND 1150
ON CONFLICT (product_id, size) DO NOTHING;

-- 3. Map every product into the Lattafa brand collection
INSERT INTO public.product_collections (product_id, collection_id)
SELECT id, 'lattafa' FROM public.products WHERE id BETWEEN 1100 AND 1150
ON CONFLICT DO NOTHING;

-- 4. Map products into their sub-line collections
INSERT INTO public.product_collections (product_id, collection_id)
SELECT p.id, l.collection_id
FROM public.products p
JOIN (VALUES
    ('ameerat-al-arab', ARRAY[1119, 1120, 1121]),
    ('ana-abiyedh', ARRAY[1122, 1123, 1124]),
    ('asad', ARRAY[1107, 1108, 1109]),
    ('badee-al-oud', ARRAY[1110, 1111, 1112, 1113, 1114]),
    ('confession', ARRAY[1138, 1139]),
    ('eclaire', ARRAY[1128, 1129, 1130]),
    ('fakhar', ARRAY[1115, 1116, 1117, 1118]),
    ('hayaati', ARRAY[1145, 1146, 1147, 1148]),
    ('khamrah', ARRAY[1100, 1101, 1102]),
    ('mahir', ARRAY[1135, 1136, 1137]),
    ('mayar', ARRAY[1125, 1126, 1127]),
    ('musammam', ARRAY[1143, 1144]),
    ('noble', ARRAY[1133, 1134]),
    ('rave-now', ARRAY[1149, 1150]),
    ('teriaq', ARRAY[1141, 1142]),
    ('yara', ARRAY[1103, 1104, 1105, 1106])
) AS l(collection_id, product_ids) ON p.id = ANY(l.product_ids)
ON CONFLICT DO NOTHING;
